server:
  port: 18002

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata?useSSL=false&serverTimeZone=Asia/Shanghai
    username: root
    password: root
  application:
    name: storage-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: business-service

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
seata:
  enabled: true
  service:
    vgroup-mapping:
      business-service: default
    grouplist:
      default: 127.0.0.1:8091
    disable-global-transaction: false
